//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int id { get; set; }
        public string bname { get; set; }
        public Nullable<int> c_id { get; set; }
        public Nullable<int> a_id { get; set; }
        public Nullable<int> p_id { get; set; }
        public string contents { get; set; }
        public Nullable<int> pages { get; set; }
        public Nullable<int> edition { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
